spring:
  application:
    name: mini-deposit-service

server:
  port: 2056

channel-properties:
  intrabank:
    service: IntrabankService
  instapay:
    service: InstapayService
  pesonet:
    service: PesonetService
