spring:
  application:
    name: mini-deposit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/deposit_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 2056

cbs:
  base-url: http://localhost:8080
  mock:
    enabled: true

instapay:
  base-url: http://localhost:8081
  mock:
    enabled: true

pesonet:
  base-url: http://localhost:8082
  mock:
    enabled: true
